# add stages here 
stages:
  prepare_data:
    cmd: python src/stage_01_prepare.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_01_prepare.py
      - data/data.xml
      - src/utils/common.py
      - src/utils/data_management.py
      - configs/config.yaml
    params:
      - prepare.split
      - prepare.seed
    outs:
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv

  featurize:
    cmd: python src/stage_02_featurization.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_02_featurization.py
      - artifacts/prepared/train.tsv
      - artifacts/prepared/test.tsv
      - src/utils/common.py
      - src/utils/featurize.py
      - configs/config.yaml
    params:
      - featurize.max_feature
      - featurize.ngrams
    outs:
      - artifacts/features/train.pkl
      - artifacts/features/test.pkl

  training:
    cmd: python src/stage_03_train.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/features/train.pkl
      - src/utils/common.py
      - src/utils/featurize.py
      - configs/config.yaml
    params:
      - train.seed
      - train.n_est
      - train.min_split
    outs:
      - artifacts/model/model.pkl

  evaluate:
    cmd: python src/stage_04_evaluate.py --config=configs/config.yaml --params=params.yaml
    deps:
      - src/stage_04_evaluate.py
      - artifacts/features/test.pkl
      - src/utils/common.py
      - src/utils/featurize.py
      - configs/config.yaml
      - artifacts/model/model.pkl
    metrics:
      - score.json:
          cache: false
    plots:
      - prc.json:
          cache: false
          x: recall
          y: precision
      
      - roc.json:
          cache: false
          x: fpr
          y: tpr

  run_plot_cmd:
    cmd: dvc plots diff






