
# https://cml.dev/
# add ci-cd steps here

name: train_nlp_dvc

on: [push]

jobs:
  deploy-runner:
    runs-on: [ubuntu-latest]
    steps:
      - uses: iterative/setup-cml@v1
      - uses: actions/checkout@v2
      - name: "Deploy runner in EC2 "
        shell: bash
        env: 
          REPO_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cml-runner \
          -- cloud aws \
          -- cloud_region us_east \
          -- cloud-type=m \ # t2.micro or m
          -- labels= cml-runner


  model-training:
    needs: deploy-runner
    runs-on: [self-hosted,cml-runner]
    container: docker://iterativeai/cml:0-dvc2-base1
    
    
    steps:
      - uses: actions/checkout@v2

      - name: "Train my model"
        env:
          REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}

        run: |  # | will run all the commands in sequence
          # ML workflow commands
          pip install --upgrade pip
          pip3 install -r requirements.txt

          dvc repro -v ## v --> verbose
          echo "## REPORTS" >> report.md
          echo "## METRICS" >> report.md
          cat score.json >> report.md

          cml-send-comment report.md ## CML COMMAND USE TO COMMENT ON LAST COMMAND



